--------------------------------------------------------
--  File created - Wednesday-June-01-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOSEN
--------------------------------------------------------

  CREATE TABLE "HR"."DOSEN" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAMA" VARCHAR2(50 BYTE), 
	"ALAMAT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.DOSEN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index DOSEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."DOSEN_PK" ON "HR"."DOSEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DOSEN
--------------------------------------------------------

  ALTER TABLE "HR"."DOSEN" ADD CONSTRAINT "DOSEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."DOSEN" MODIFY ("ALAMAT" NOT NULL ENABLE);
  ALTER TABLE "HR"."DOSEN" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "HR"."DOSEN" MODIFY ("ID" NOT NULL ENABLE);
