--------------------------------------------------------
--  File created - Wednesday-June-01-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAHASISWA
--------------------------------------------------------

  CREATE TABLE "HR"."MAHASISWA" 
   (	"NIM" VARCHAR2(9 BYTE), 
	"NAMA" VARCHAR2(50 BYTE), 
	"ALAMAT" VARCHAR2(100 BYTE), 
	"TEMPAT_LAHIR" VARCHAR2(20 BYTE), 
	"TANGGAL_LAHIR" VARCHAR2(20 BYTE), 
	"JURUSAN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MAHASISWA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MAHASISWA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MAHASISWA_PK" ON "HR"."MAHASISWA" ("NIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MAHASISWA
--------------------------------------------------------

  ALTER TABLE "HR"."MAHASISWA" ADD CONSTRAINT "MAHASISWA_PK" PRIMARY KEY ("NIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("JURUSAN" NOT NULL ENABLE);
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("TANGGAL_LAHIR" NOT NULL ENABLE);
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("TEMPAT_LAHIR" NOT NULL ENABLE);
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("ALAMAT" NOT NULL ENABLE);
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "HR"."MAHASISWA" MODIFY ("NIM" NOT NULL ENABLE);
